# version: '3.8'
services:
  db:
    container_name: eze.pg.container
    image: postgres:latest
    environment:
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: eze
        POSTGRES_DB: imdb
    ports:
        - "5432:5432"
    networks:
        #- imdb.container.network
        - default
    volumes:
        - ./scrapy_dump.sql:/docker-entrypoint-initdb.d/scrapy-dump.sql
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -d imdb -U admin"]
        interval: 10s
        timeout: 5s
        retries: 5

  app:
    container_name: eze.app.container
    image: imdb.image
    build: .
    depends_on:
        db:
          condition: service_healthy
    links:
        - db
    networks:
        #- imdb.container.network
        - default

  pgadmin:
    container_name: eze_pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80"

# name all networks
networks:
    imdb.container.network:
        driver: bridge
